---
- hosts: ubuntu  
  become: yes
  gather_facts: yes

  vars:
    sudoers:
      - "{{ sudo_new_user }}"
    
    sudo_new_user_pass: "{{ new_user_pass }}"
    change_root_password: false

  
  roles:
   - role: ../roles/create-sudoers